travis:
  secure:
    BINSTAR_TOKEN: WRWvEJ/UbqEYY6SX5MFgBUQifgMr3T6DgXE67fIThpPMt4oigWL51ERrfKf35NWkXdSD2pq1hz3Gup4DVFcToum+sg9zv6YA/TRUBB4IqAsjqvFPgf5OsnDh35T6iBaxLYv/z3slohXPc78qxtKQ85RnCoZ5GkVYaOuxx59PMopZ/i5SNKVKUWYL5L0j9yvEqb5u+POZ6+z+7XyVu6zrty8csgFCkUdCcKs33jOLQObh7wRJZ31J8lHyI3Ode8ZmSMgRW3+TsOe0skAj+4TmWyQPvZqhkFjU+aOPr3tpnXeyrd+R54VsP2MYmnBmgMMzxEHf43TsBkC/XzTlWglGAT7m9g1EzpfZMHJXUYriw1wV7DKr1U0sNj/lZYJhrEIJoyYlSEClfjrpx4192E7yxK8k1C1HMYROmODwJr+f6R6bEguYqTFo5WLabWzEdSWP6tIHXc+GbVyXeocB/o97/Apdnz6ta0LP3SIEj/Pmg/AuWI+TgIecO0DoOxq/c7u7eml/gTExPOh16OcvuZfpxvr6/7ngDBfkUUkm42WOU0P4qZ0GIEpTiOHnpnFF7pyJeLubDw4x07S0pLIkmc/5aTfc6dQUYzkQZpuZ7ReaDK2JjIfCYJ46eLgy7Ge6oFCiCrw5XSRtXhf0DeD9wrx8kPF+k6vMWTAvl0nipFxYcb8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
